### PR TITLE
Modify to allow alternate ripping commands via optional scripts

### PR DESCRIPTION
**Pull request by wilddeej**
Addresses Issue #16 by checking for the presence of executable scripts in the same directory as `ripper.sh`:

- `BLURAYrip.sh` to be used as an alternate to the BluRay DVD ripping commands from `ripper.sh`,
- `DVDrip.sh` to be used as an alternate to the DVD ripping commands from `ripper.sh`,
- `CDrip.sh` to be used as an alternate to the audio CD ripping commands from `ripper.sh`,
- `DATArip.sh` to be used as an alternate to the DATA CD ripping commands from `ripper.sh`

If the relevant script is found, it will be executed as an override to the associated command(s) within `ripper.sh`; if none of the defined scripts is found, no changes to previous `ripper.sh` operation occurs.
 
Additionally includes some minor code re-structuring to eliminate duplicate code and to assure that the defined variables are used reliably and consistently throughout the script.

### CODE REVIEW

**Comment by rix1337** [comment]
Thanks for the pr - this looks good.

**Comment by wilddeej** [comment]
Great - glad you like the change!  I'd be happy to make updates to the
README.md file to document this new functionality.  I'm thinking the answer
to the "How do I set ripper to do something else?" FAQ question could have
an additional paragraph for this purpose.  Does that make sense to you?

**Comment by rix1337** [comment]
Totally, please do so by sending another PR - I hardly ever grant repo edit rights.

**Comment by wilddeej** [comment]
Works for me!

**Pull request merged**
