### PR TITLE
Enhancement - Use MakeMKV profiles when ripping BD/DVD

### PR DESCRIPTION
**Pull request by RandomNinjaAtk**
This patch includes the default MakeMKV profile for track/audio/subtitle selection. This patch will enable the user to customize the default track/audio/subtitle selection when ripping Blu-rays or DVDs.

### CODE REVIEW

**Comment by rix1337** [comment]
Hi, thanks for providing this. Do we really need this PR, since everyone should be able to adapt the script to their liking, locally?

It seems the GUI is required to set up the default profile, also. The default.mmcp.xml you provided does not look like a default file from MakeMKV. Do you have documentation on the whole mmcp file structure?

**Comment by RandomNinjaAtk** [comment]
By integrating into the docker, I was hoping to prevent it from overwriting my changes in the future or if I ever need to redeploy the docker, I wouldn't need to remember to manually edit them encase I forget.

As for the default file, the file I uploaded is the default file found in my Windows MakeMKV install and isn't edited. So it should be the normal one...

**Comment by rix1337** [comment]
Ok, ill consider adding this in the future. Just have to check some things first.

If you are worried about losing these settings on reinstall, just create a new github repo, add a file called `Dockerfile`

on the top write
`from rix1337/docker-ripper` and then do your modifications:

much similar to what I did here:
https://github.com/rix1337/docker-sonarr-processing/blob/master/Dockerfile

you can then create an automated build on dockerhub & even create an automated trigger, that updates your baseimage whenever I update mine.

I do automatic builds for this docker-ripper, whenever another makemkv-docker is being updated.

Its great 👍

**Comment by RandomNinjaAtk** [comment]
I would be considered very new user to all these tools and don't have the experience at this time that I want to take on maintaining my own. I appreciate the suggestion and may have to look into it in the future. That's why I'd rather contribute if I can.

Have you seen this project? https://github.com/ahnooie/automatic-ripping-machine 

Its very similar to this but not designed for docker yet. I helped with the Plex portion on it and it takes your setup a bit further...

**Pull request merged**
