### PR TITLE
add docker-compose file

### PR DESCRIPTION
**Pull request by crazyoptimist**
Run command:
Check your device mount point before you run the container!
```bash
docker-compose up -d
```

### CODE REVIEW

**Comment by rix1337** [comment]
Thank you. Not using compose myself. I have removed the "root" sub folder as it seems unnecessary.
Am I right to assume, the paths are relative to where you run the compose script?

**Comment by crazyoptimist** [comment]
Thank you for reviewing @rix1337 !

**Comment by crazyoptimist** [comment]
> Thank you. Not using compose myself. I have removed the "root" sub folder as it seems unnecessary.
> Am I right to assume, the paths are relative to where you run the compose script?

Sure

**Comment by rix1337** [comment]
Thanks for the input. Am super happy someone else found this so useful, they contributed 🎉

**Pull request merged**
